CREATE TABLE CLIENT_MASTER
(
    CLIENT_NO VARCHAR(6) PRIMARY KEY CHECK (CLIENT_NO LIKE 'C_____'),
    NAME      VARCHAR(20) NOT NULL,
    ADDRESS1  VARCHAR(30),
    ADDRESS2  VARCHAR(30),
    CITY      VARCHAR(15),
    PINCODE   INTEGER,
    STATE     VARCHAR(15),
    BAL_DUE   DECIMAL(10, 2)
);

CREATE TABLE PRODUCT_MASTER
(
    PRODUCT_NO     VARCHAR(6) PRIMARY KEY CHECK (PRODUCT_NO LIKE 'P_____'),
    DESCRIPTION    VARCHAR(15)   NOT NULL,
    PROFIT_PERCENT DECIMAL(4, 2) NOT NULL,
    UNIT_MEASURE   VARCHAR(10)   NOT NULL,
    QTY_ON_HAND    INTEGER       NOT NULL,
    REORDER_LVL    INTEGER       NOT NULL,
    SELL_PRICE     DECIMAL(8, 2) NOT NULL CHECK ( SELL_PRICE >= 0 ),
    COST_PRICE     DECIMAL(8, 2) NOT NULL CHECK ( COST_PRICE >= 0 )
);

CREATE TABLE SALESMAN_MASTER
(
    SALESMAN_NO   VARCHAR(6) PRIMARY KEY CHECK (SALESMAN_NO LIKE 'S_____'),
    SALESMAN_NAME VARCHAR(20)   NOT NULL,
    ADDRESS1      VARCHAR(30)   NOT NULL,
    ADDRESS2      VARCHAR(30),
    CITY          VARCHAR(15),
    PINCODE       INTEGER,
    STATE         VARCHAR(15),
    SALE_AMT      DECIMAL(8, 2) NOT NULL CHECK ( YTD_SALES >= 0 ),
    TOT_TOGET     DECIMAL(6, 2) NOT NULL CHECK ( TOT_TOGET >= 0 ),
    YTD_SALES     DECIMAL(6, 2) NOT NULL,
    REMARKS       VARCHAR(60)
);

CREATE TABLE SALES_ORDER
(
    ORDER_NO     VARCHAR(6) PRIMARY KEY CHECK (ORDER_NO LIKE 'O_____'),
    CLIENT_NO    VARCHAR(6) REFERENCES client_master (CLIENT_NO),
    SALESMAN_NO  VARCHAR(6) REFERENCES salesman_master (SALESMAN_NO),
    ORDER_DATE   DATE NOT NULL,
    DELY_TYPE    CHAR DEFAULT 'F',
    DELY_DATE    DATE CHECK (DELY_DATE >= ORDER_DATE),
    BILL_YORN    CHAR,
    ORDER_STATUS VARCHAR(10) CHECK ( ORDER_STATUS IN ('InProcess', 'Fulfilled', 'BackOrder', 'Cancelled') )
);

CREATE TABLE SALES_ORDER_DETAILS
(
    ORDER_NO       VARCHAR(6) REFERENCES sales_order (ORDER_NO),
    PRODUCT_NO     VARCHAR(6) REFERENCES product_master (PRODUCT_NO),
    QTY_ORDERED    INTEGER,
    QTY_DISPATCHED INTEGER,
    PRODUCT_RATE   DECIMAL(10, 2)
);
